### ISSUE TITLE
장이 열리지 않는 날을 입력했더니 에러가 발생하는데... 이건 에러일까요?

### ISSUE THREAD

**Issue by min7014** [CoreDotToday/CoreDotFinance#124]
```
from coredotfinance.data import KrxReader
krx = KrxReader()
dataframe = krx.read('코스피', start='2021-10-17', end='2021-10-17', kind='index')
print(dataframe.head(10))
```

```
Traceback (most recent call last):
  File "c:/Users/min/Desktop/종합주가지수/test.py", line 3, in <module>
    dataframe = krx.read('코스피', start='2021-10-17', end='2021-10-17', kind='index')
  File "C:\Python\Python38\lib\site-packages\coredotfinance\data.py", line 228, in read
    dataframe = data_reader(
  File "C:\Python\Python38\lib\site-packages\coredotfinance\krx\api\data_reader.py", line 80, in data_reader
    dataframe = get_dataframe(krx_data, korean_columns)
  File "C:\Python\Python38\lib\site-packages\coredotfinance\krx\core\process.py", line 30, in get_dataframe
    _check_data_validation(krx_data)
  File "C:\Python\Python38\lib\site-packages\coredotfinance\krx\core\process.py", line 47, in _check_data_validation
    raise Exception("No data, Check parameters")
Exception: No data, Check parameters
```

**Comment by min7014** [comment]
네 고맙습니다.

**Comment by DavidKimDY** [comment]
좋은 아이디어네요. 
해당 날짜의 데이터가 없음을 알려주는것이 더 사용성에 좋다고 판단합니다.
만약 비어있는 데이터를 내놓게 되면 사용자는 많은 코드가 모두 진행되고 나서야 데이터가 비어있는 것을 발견하게 되고 자원을 낭비하게 됩니다. Error는 사용자가 제어할 수 있습니다.

**Comment by min7014** [comment]
```
try:

except:
```
로 제어하란 의미였군요. 고맙습니다.
