### ISSUE TITLE
거래정지 종목의 출력에 대하여...

### ISSUE THREAD

**Issue by min7014** [CoreDotToday/CoreDotFinance#126]
거래정지 종목의 경우 마지막 날의 종가가 그대로 사용되야 되지 않을까 합니다.

주식 정보를 보면 보통 그렇게 되어 있어서 문의 드립니다.

```
import datetime
import os
from dateutil.relativedelta import relativedelta
from coredotfinance.data import KrxReader

krx = KrxReader()

i='002420' # 2021.10.20 현재 날짜에 거래정지 종목

dataframe = krx.read(i, 
            start=str(datetime.datetime.today()-relativedelta(days=30))[0:10], 
            end=str(datetime.datetime.today())[0:10],
            adjust=True)
```
```
세기상사
Traceback (most recent call last):
  File "C:\Python\Python38\lib\site-packages\pandas\core\ops\array_ops.py", line 166, in _na_arithmetic_op
    result = func(left, right)
  File "C:\Python\Python38\lib\site-packages\pandas\core\computation\expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "C:\Python\Python38\lib\site-packages\pandas\core\computation\expressions.py", line 69, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for /: 'str' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/min/Desktop/종합주가지수/test2.py", line 10, in <module>
    dataframe = krx.read(i,
  File "C:\Python\Python38\lib\site-packages\coredotfinance\data.py", line 246, in read
    return option.options(dataframe=dataframe, **kwargs)
  File "C:\Python\Python38\lib\site-packages\coredotfinance\krx\core\option.py", line 76, in options
    dataframe = adjust_price(dataframe)
  File "C:\Python\Python38\lib\site-packages\coredotfinance\krx\core\option.py", line 47, in adjust_price
    dataframe[column] = (data / standard_ratio).astype(int)
  File "C:\Python\Python38\lib\site-packages\pandas\core\ops\common.py", line 69, in new_method
    return method(self, other)
  File "C:\Python\Python38\lib\site-packages\pandas\core\arraylike.py", line 116, in __truediv__
    return self._arith_method(other, operator.truediv)
  File "C:\Python\Python38\lib\site-packages\pandas\core\series.py", line 5526, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "C:\Python\Python38\lib\site-packages\pandas\core\ops\array_ops.py", line 224, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "C:\Python\Python38\lib\site-packages\pandas\core\ops\array_ops.py", line 173, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
  File "C:\Python\Python38\lib\site-packages\pandas\core\ops\array_ops.py", line 112, in _masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])
TypeError: unsupported operand type(s) for /: 'str' and 'float'
```

**Comment by DavidKimDY** [comment]
위 에러는 질문하신 분께서 작성하신 코드에서 발생한 에러입니다.
```
TypeError: unsupported operand type(s) for /: 'str' and 'float'
```
Error 메세지를 잘 살펴보시길 바랍니다.

**Comment by DavidKimDY** [comment]
에러는 수정했습니다. 에러 내용은 PR을 참고하시고 1.2.2 버전으로 업그레이드 해서 쓰시면 됩니다.

**Comment by min7014** [comment]
확인했습니다. 고맙습니다.
